// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_TpkPMBjdD2Z00JItLcLTCoyyt9cdL38',
    appId: '1:400547297195:web:c26c222df107347dd944ee',
    messagingSenderId: '400547297195',
    projectId: 'chatterbox-2fc7b',
    authDomain: 'chatterbox-2fc7b.firebaseapp.com',
    databaseURL: 'https://chatterbox-2fc7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatterbox-2fc7b.appspot.com',
    measurementId: 'G-4HKXV0G515',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABqM0UdEpLjfYc34Fa0WX1dwDZehJtbfQ',
    appId: '1:400547297195:android:cee60fe7fed6d7c5d944ee',
    messagingSenderId: '400547297195',
    projectId: 'chatterbox-2fc7b',
    databaseURL: 'https://chatterbox-2fc7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatterbox-2fc7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_k4qLWJojHyztMZvFjEIQ0afgC0nJho',
    appId: '1:400547297195:ios:73126b8478541fe3d944ee',
    messagingSenderId: '400547297195',
    projectId: 'chatterbox-2fc7b',
    databaseURL: 'https://chatterbox-2fc7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatterbox-2fc7b.appspot.com',
    iosBundleId: 'com.example.chatterbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg_k4qLWJojHyztMZvFjEIQ0afgC0nJho',
    appId: '1:400547297195:ios:c1ab368fbc4f2bd6d944ee',
    messagingSenderId: '400547297195',
    projectId: 'chatterbox-2fc7b',
    databaseURL: 'https://chatterbox-2fc7b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chatterbox-2fc7b.appspot.com',
    iosBundleId: 'com.example.chatterbox.RunnerTests',
  );
}
